# Generated by Django 2.0.1 on 2018-01-26 20:22

from django.db import migrations, models


class Migration(migrations.Migration):

    initial = True

    dependencies = [
    ]

    operations = [
        migrations.CreateModel(
            name='CotacaoRequest',
            fields=[
                ('id', models.AutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('name', models.CharField(max_length=200, null=True, verbose_name='Nome')),
                ('email', models.CharField(max_length=200, null=True, verbose_name='Email')),
                ('vehicle_type', models.CharField(blank=True, max_length=200, null=True, verbose_name='Tipo de veículo')),
                ('board_number', models.CharField(blank=True, max_length=8, null=True, verbose_name='Número de placa')),
            ],
            options={
                'verbose_name': 'Pedido de Cotação',
                'verbose_name_plural': 'Pedidos de Cotação',
                'db_table': 'CotacaoRequest',
            },
        ),
    ]
